[package]
name = "source-analyzer"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"

[dependencies]
anyhow = "1.0.104"
anstream = "1.0.0"
anstyle = "1.0.14"
clap = { version = "4.6.7", features = ["derive"] }
kva = { version = "0.2.0", default-features = false, features = ["std", "text"] }
source-vpk = "0.5.0"
toml = { version = "1.0.7", default-features = false, features = ["parse", "serde"] }
zip = { version = "8.6.0", default-features = false, features = ["deflate"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
strip = true

[profile.dev]
debug = "line-tables-only"
split-debuginfo = "unpacked"

[profile.dev.package."*"]
debug = false
